# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies

      - run:
          name: install dependencies
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
            /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
            export PATH=$HOME/conda/bin:$PATH
            $HOME/conda/bin/pip install sregistry[all]
            chmod u+x ~/repo/.circleci/*.sh
            /bin/bash ~/repo/.circleci/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies

      - run:
          name: build container
          command: |
            cd ~/repo
            # yes | ./demonstrate.sh
            make test
            mkdir -p build && cp *.simg build
            mkdir -p build && cp Singularity* build

      - store_artifacts:
          path: ~/repo/build
          destination: singularity-containers
